// <auto-generated />
using System;
using CarRental.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRental.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260521131955_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CarRental.Core.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Chassis")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FabricationYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FuelConsumption")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Horsepower")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Seats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Transmission")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "BMW",
                            Chassis = "Sedan",
                            Description = "Elegant sedan with premium comfort and sporty handling, ideal for business trips.",
                            EngineType = "2.0L Diesel",
                            FabricationYear = 2023,
                            FuelConsumption = "6.2 L/100km",
                            Horsepower = 190,
                            IsDeleted = false,
                            LicensePlate = "B01RRR",
                            Location = "București",
                            Model = "Series 3",
                            PricePerDay = 75.00m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "BMW",
                            Chassis = "Sedan",
                            Description = "Sporty rear-wheel-drive sedan delivering pure driving pleasure on any road.",
                            EngineType = "2.0L Petrol",
                            FabricationYear = 2021,
                            FuelConsumption = "6.8 L/100km",
                            Horsepower = 184,
                            IsDeleted = false,
                            LicensePlate = "CJ01RRR",
                            Location = "Cluj-Napoca",
                            Model = "Series 3",
                            PricePerDay = 75.00m,
                            Seats = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "BMW",
                            Chassis = "SUV",
                            Description = "Premium SUV with spacious interior and powerful diesel engine for long journeys.",
                            EngineType = "3.0L Diesel",
                            FabricationYear = 2024,
                            FuelConsumption = "9.5 L/100km",
                            Horsepower = 286,
                            IsDeleted = false,
                            LicensePlate = "B02RRR",
                            Location = "București",
                            Model = "X5",
                            PricePerDay = 120.00m,
                            Seats = 7,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "BMW",
                            Chassis = "SUV",
                            Description = "High-performance luxury SUV with xDrive AWD and dynamic sport suspension.",
                            EngineType = "3.0L Petrol",
                            FabricationYear = 2022,
                            FuelConsumption = "10.1 L/100km",
                            Horsepower = 340,
                            IsDeleted = false,
                            LicensePlate = "TM01RRR",
                            Location = "Timișoara",
                            Model = "X5",
                            PricePerDay = 120.00m,
                            Seats = 7,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "BMW",
                            Chassis = "Sedan",
                            Description = "Executive sedan combining luxury, technology and efficient diesel performance.",
                            EngineType = "2.0L Diesel",
                            FabricationYear = 2023,
                            FuelConsumption = "7.0 L/100km",
                            Horsepower = 197,
                            IsDeleted = false,
                            LicensePlate = "BV01RRR",
                            Location = "Brașov",
                            Model = "Series 5",
                            PricePerDay = 95.00m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Mercedes",
                            Chassis = "Sedan",
                            Description = "Luxury sedan with cutting-edge MBUX technology and refined interior design.",
                            EngineType = "2.0L Diesel",
                            FabricationYear = 2024,
                            FuelConsumption = "7.5 L/100km",
                            Horsepower = 204,
                            IsDeleted = false,
                            LicensePlate = "B03RRR",
                            Location = "București",
                            Model = "C-Class",
                            PricePerDay = 85.00m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Mercedes",
                            Chassis = "Sedan",
                            Description = "Agile and engaging sedan with turbocharged petrol engine and manual gearbox.",
                            EngineType = "1.5L Petrol Turbo",
                            FabricationYear = 2022,
                            FuelConsumption = "7.8 L/100km",
                            Horsepower = 170,
                            IsDeleted = false,
                            LicensePlate = "IS01RRR",
                            Location = "Iași",
                            Model = "C-Class",
                            PricePerDay = 85.00m,
                            Seats = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Mercedes",
                            Chassis = "Sedan",
                            Description = "Flagship sedan offering supreme comfort, prestige and whisper-quiet cabin.",
                            EngineType = "2.0L Diesel",
                            FabricationYear = 2023,
                            FuelConsumption = "8.0 L/100km",
                            Horsepower = 220,
                            IsDeleted = false,
                            LicensePlate = "B04RRR",
                            Location = "București",
                            Model = "E-Class",
                            PricePerDay = 110.00m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Mercedes",
                            Chassis = "SUV",
                            Description = "Versatile luxury SUV with turbocharged power and agile handling.",
                            EngineType = "2.0L Petrol Turbo",
                            FabricationYear = 2024,
                            FuelConsumption = "8.5 L/100km",
                            Horsepower = 258,
                            IsDeleted = false,
                            LicensePlate = "CJ02RRR",
                            Location = "Cluj-Napoca",
                            Model = "GLC",
                            PricePerDay = 105.00m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Mercedes",
                            Chassis = "SUV",
                            Description = "Full-size luxury SUV with 7 seats, air suspension and all-terrain capability.",
                            EngineType = "3.0L Diesel",
                            FabricationYear = 2023,
                            FuelConsumption = "9.8 L/100km",
                            Horsepower = 330,
                            IsDeleted = false,
                            LicensePlate = "TM02RRR",
                            Location = "Timișoara",
                            Model = "GLE",
                            PricePerDay = 130.00m,
                            Seats = 7,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Audi",
                            Chassis = "Sedan",
                            Description = "Quattro all-wheel drive with a sophisticated interior and responsive TFSI engine.",
                            EngineType = "2.0L TFSI Petrol",
                            FabricationYear = 2023,
                            FuelConsumption = "5.8 L/100km",
                            Horsepower = 204,
                            IsDeleted = false,
                            LicensePlate = "B05RRR",
                            Location = "București",
                            Model = "A4",
                            PricePerDay = 70.00m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Audi",
                            Chassis = "Sedan",
                            Description = "Efficient TDI diesel sedan with precise handling and excellent fuel economy.",
                            EngineType = "2.0L TDI Diesel",
                            FabricationYear = 2021,
                            FuelConsumption = "6.1 L/100km",
                            Horsepower = 163,
                            IsDeleted = false,
                            LicensePlate = "BV02RRR",
                            Location = "Brașov",
                            Model = "A4",
                            PricePerDay = 70.00m,
                            Seats = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Audi",
                            Chassis = "Sedan",
                            Description = "Business-class sedan with advanced Virtual Cockpit and smooth TDI power.",
                            EngineType = "2.0L TDI Diesel",
                            FabricationYear = 2024,
                            FuelConsumption = "6.5 L/100km",
                            Horsepower = 204,
                            IsDeleted = false,
                            LicensePlate = "CJ03RRR",
                            Location = "Cluj-Napoca",
                            Model = "A6",
                            PricePerDay = 90.00m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Audi",
                            Chassis = "SUV",
                            Description = "Large luxury SUV with three rows, quattro AWD and potent TFSI V6 engine.",
                            EngineType = "3.0L TFSI Petrol",
                            FabricationYear = 2023,
                            FuelConsumption = "9.2 L/100km",
                            Horsepower = 340,
                            IsDeleted = false,
                            LicensePlate = "B06RRR",
                            Location = "București",
                            Model = "Q7",
                            PricePerDay = 125.00m,
                            Seats = 7,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Audi",
                            Chassis = "SUV",
                            Description = "Compact luxury SUV with sporty dynamics, refined comfort and efficient diesel.",
                            EngineType = "2.0L TDI Diesel",
                            FabricationYear = 2022,
                            FuelConsumption = "7.0 L/100km",
                            Horsepower = 204,
                            IsDeleted = false,
                            LicensePlate = "IS02RRR",
                            Location = "Iași",
                            Model = "Q5",
                            PricePerDay = 100.00m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Toyota",
                            Chassis = "Sedan",
                            Description = "Reliable hybrid sedan with outstanding fuel economy, perfect for city commutes.",
                            EngineType = "1.8L Hybrid",
                            FabricationYear = 2024,
                            FuelConsumption = "4.5 L/100km",
                            Horsepower = 140,
                            IsDeleted = false,
                            LicensePlate = "B07RRR",
                            Location = "București",
                            Model = "Corolla",
                            PricePerDay = 45.00m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Toyota",
                            Chassis = "Sedan",
                            Description = "Dependable compact sedan with low running costs and engaging manual gearbox.",
                            EngineType = "1.6L Petrol",
                            FabricationYear = 2022,
                            FuelConsumption = "4.8 L/100km",
                            Horsepower = 132,
                            IsDeleted = false,
                            LicensePlate = "CJ04RRR",
                            Location = "Cluj-Napoca",
                            Model = "Corolla",
                            PricePerDay = 45.00m,
                            Seats = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Toyota",
                            Chassis = "SUV",
                            Description = "Popular crossover SUV with hybrid efficiency and spacious cargo area.",
                            EngineType = "2.5L Hybrid",
                            FabricationYear = 2023,
                            FuelConsumption = "5.5 L/100km",
                            Horsepower = 222,
                            IsDeleted = false,
                            LicensePlate = "BV03RRR",
                            Location = "Brașov",
                            Model = "RAV4",
                            PricePerDay = 65.00m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Toyota",
                            Chassis = "SUV",
                            Description = "Rugged crossover with confident road manners and practical manual transmission.",
                            EngineType = "2.0L Petrol",
                            FabricationYear = 2021,
                            FuelConsumption = "5.8 L/100km",
                            Horsepower = 173,
                            IsDeleted = false,
                            LicensePlate = "TM03RRR",
                            Location = "Timișoara",
                            Model = "RAV4",
                            PricePerDay = 65.00m,
                            Seats = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Toyota",
                            Chassis = "SUV",
                            Description = "Legendary off-road SUV with luxurious amenities, V6 diesel power and 7-seat capacity.",
                            EngineType = "3.5L V6 Diesel",
                            FabricationYear = 2024,
                            FuelConsumption = "10.5 L/100km",
                            Horsepower = 305,
                            IsDeleted = false,
                            LicensePlate = "B08RRR",
                            Location = "București",
                            Model = "Land Cruiser",
                            PricePerDay = 140.00m,
                            Seats = 7,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Volkswagen",
                            Chassis = "Hatchback",
                            Description = "Iconic hatchback with German engineering, nimble handling and turbocharged TSI power.",
                            EngineType = "1.5L TSI Petrol",
                            FabricationYear = 2023,
                            FuelConsumption = "5.2 L/100km",
                            Horsepower = 150,
                            IsDeleted = false,
                            LicensePlate = "B09RRR",
                            Location = "București",
                            Model = "Golf",
                            PricePerDay = 50.00m,
                            Seats = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Volkswagen",
                            Chassis = "Hatchback",
                            Description = "Compact and efficient hatchback with refined ride quality and intuitive infotainment.",
                            EngineType = "1.0L TSI Petrol",
                            FabricationYear = 2021,
                            FuelConsumption = "5.5 L/100km",
                            Horsepower = 110,
                            IsDeleted = false,
                            LicensePlate = "IS03RRR",
                            Location = "Iași",
                            Model = "Golf",
                            PricePerDay = 50.00m,
                            Seats = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Volkswagen",
                            Chassis = "Sedan",
                            Description = "Spacious family sedan with premium features, digital cockpit and smooth TSI engine.",
                            EngineType = "1.5L TSI Petrol",
                            FabricationYear = 2024,
                            FuelConsumption = "5.8 L/100km",
                            Horsepower = 150,
                            IsDeleted = false,
                            LicensePlate = "CJ05RRR",
                            Location = "Cluj-Napoca",
                            Model = "Passat",
                            PricePerDay = 65.00m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Volkswagen",
                            Chassis = "SUV",
                            Description = "Compact SUV with versatile interior, confident road presence and powerful TSI engine.",
                            EngineType = "2.0L TSI Petrol",
                            FabricationYear = 2023,
                            FuelConsumption = "6.5 L/100km",
                            Horsepower = 190,
                            IsDeleted = false,
                            LicensePlate = "BV04RRR",
                            Location = "Brașov",
                            Model = "Tiguan",
                            PricePerDay = 70.00m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Volkswagen",
                            Chassis = "SUV",
                            Description = "Flagship SUV combining luxury with off-road prowess and mighty V6 TDI diesel.",
                            EngineType = "3.0L V6 TDI Diesel",
                            FabricationYear = 2024,
                            FuelConsumption = "9.0 L/100km",
                            Horsepower = 286,
                            IsDeleted = false,
                            LicensePlate = "TM04RRR",
                            Location = "Timișoara",
                            Model = "Touareg",
                            PricePerDay = 115.00m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Dacia",
                            Chassis = "Sedan",
                            Description = "Affordable and practical sedan with unbeatable value and low running costs.",
                            EngineType = "1.0L SCe Petrol",
                            FabricationYear = 2024,
                            FuelConsumption = "5.0 L/100km",
                            Horsepower = 91,
                            IsDeleted = false,
                            LicensePlate = "B10RRR",
                            Location = "București",
                            Model = "Logan",
                            PricePerDay = 25.00m,
                            Seats = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Dacia",
                            Chassis = "Sedan",
                            Description = "Budget-friendly sedan with generous boot space and peppy TCe turbo engine.",
                            EngineType = "1.0L TCe Petrol",
                            FabricationYear = 2022,
                            FuelConsumption = "5.3 L/100km",
                            Horsepower = 100,
                            IsDeleted = false,
                            LicensePlate = "CJ06RRR",
                            Location = "Cluj-Napoca",
                            Model = "Logan",
                            PricePerDay = 25.00m,
                            Seats = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 28,
                            Brand = "Dacia",
                            Chassis = "SUV",
                            Description = "Rugged and affordable SUV with diesel efficiency, perfect for Romanian mountain roads.",
                            EngineType = "1.5L Blue dCi Diesel",
                            FabricationYear = 2024,
                            FuelConsumption = "5.8 L/100km",
                            Horsepower = 115,
                            IsDeleted = false,
                            LicensePlate = "B11RRR",
                            Location = "București",
                            Model = "Duster",
                            PricePerDay = 40.00m,
                            Seats = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 29,
                            Brand = "Dacia",
                            Chassis = "SUV",
                            Description = "Versatile compact SUV with TCe petrol power and confident off-road stance.",
                            EngineType = "1.3L TCe Petrol",
                            FabricationYear = 2022,
                            FuelConsumption = "6.2 L/100km",
                            Horsepower = 131,
                            IsDeleted = false,
                            LicensePlate = "BV05RRR",
                            Location = "Brașov",
                            Model = "Duster",
                            PricePerDay = 40.00m,
                            Seats = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Dacia",
                            Chassis = "MPV",
                            Description = "7-seat family MPV with incredible value, modern design and nimble city manners.",
                            EngineType = "1.0L TCe Petrol",
                            FabricationYear = 2024,
                            FuelConsumption = "5.5 L/100km",
                            Horsepower = 110,
                            IsDeleted = false,
                            LicensePlate = "IS04RRR",
                            Location = "Iași",
                            Model = "Jogger",
                            PricePerDay = 35.00m,
                            Seats = 7,
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Ford",
                            Chassis = "Hatchback",
                            Description = "Dynamic hatchback with sharp handling, EcoBoost efficiency and modern connectivity.",
                            EngineType = "1.0L EcoBoost Petrol",
                            FabricationYear = 2023,
                            FuelConsumption = "5.0 L/100km",
                            Horsepower = 125,
                            IsDeleted = false,
                            LicensePlate = "B12RRR",
                            Location = "București",
                            Model = "Focus",
                            PricePerDay = 45.00m,
                            Seats = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Ford",
                            Chassis = "Hatchback",
                            Description = "Refined hatchback with smooth automatic transmission and responsive EcoBoost turbo.",
                            EngineType = "1.5L EcoBoost Petrol",
                            FabricationYear = 2021,
                            FuelConsumption = "5.3 L/100km",
                            Horsepower = 150,
                            IsDeleted = false,
                            LicensePlate = "TM05RRR",
                            Location = "Timișoara",
                            Model = "Focus",
                            PricePerDay = 45.00m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 33,
                            Brand = "Ford",
                            Chassis = "SUV",
                            Description = "Stylish crossover with plug-in hybrid drivetrain and spacious boot.",
                            EngineType = "2.5L PHEV Hybrid",
                            FabricationYear = 2024,
                            FuelConsumption = "6.0 L/100km",
                            Horsepower = 225,
                            IsDeleted = false,
                            LicensePlate = "CJ07RRR",
                            Location = "Cluj-Napoca",
                            Model = "Kuga",
                            PricePerDay = 60.00m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 34,
                            Brand = "Ford",
                            Chassis = "Coupe",
                            Description = "Legendary American muscle car with thrilling V8 performance and head-turning presence.",
                            EngineType = "5.0L V8 Petrol",
                            FabricationYear = 2023,
                            FuelConsumption = "12.5 L/100km",
                            Horsepower = 450,
                            IsDeleted = false,
                            LicensePlate = "B13RRR",
                            Location = "București",
                            Model = "Mustang",
                            PricePerDay = 150.00m,
                            Seats = 2,
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 35,
                            Brand = "Hyundai",
                            Chassis = "SUV",
                            Description = "Modern SUV with striking parametric design, hybrid power and advanced safety.",
                            EngineType = "1.6L T-GDI Hybrid",
                            FabricationYear = 2024,
                            FuelConsumption = "6.0 L/100km",
                            Horsepower = 230,
                            IsDeleted = false,
                            LicensePlate = "B14RRR",
                            Location = "București",
                            Model = "Tucson",
                            PricePerDay = 55.00m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 36,
                            Brand = "Hyundai",
                            Chassis = "SUV",
                            Description = "Practical SUV with efficient diesel engine and generous cargo capacity.",
                            EngineType = "1.6L CRDi Diesel",
                            FabricationYear = 2022,
                            FuelConsumption = "6.5 L/100km",
                            Horsepower = 136,
                            IsDeleted = false,
                            LicensePlate = "IS05RRR",
                            Location = "Iași",
                            Model = "Tucson",
                            PricePerDay = 55.00m,
                            Seats = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 37,
                            Brand = "Hyundai",
                            Chassis = "Hatchback",
                            Description = "Well-rounded hatchback with European styling, 5-year warranty and peppy T-GDI engine.",
                            EngineType = "1.0L T-GDI Petrol",
                            FabricationYear = 2023,
                            FuelConsumption = "5.2 L/100km",
                            Horsepower = 120,
                            IsDeleted = false,
                            LicensePlate = "CJ08RRR",
                            Location = "Cluj-Napoca",
                            Model = "i30",
                            PricePerDay = 40.00m,
                            Seats = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 38,
                            Brand = "Kia",
                            Chassis = "SUV",
                            Description = "Bold crossover SUV with futuristic design, hybrid efficiency and panoramic display.",
                            EngineType = "1.6L T-GDI Hybrid",
                            FabricationYear = 2024,
                            FuelConsumption = "6.2 L/100km",
                            Horsepower = 230,
                            IsDeleted = false,
                            LicensePlate = "BV06RRR",
                            Location = "Brașov",
                            Model = "Sportage",
                            PricePerDay = 55.00m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 39,
                            Brand = "Kia",
                            Chassis = "SUV",
                            Description = "Economical diesel SUV with robust build quality and 7-year manufacturer warranty.",
                            EngineType = "1.6L CRDi Diesel",
                            FabricationYear = 2022,
                            FuelConsumption = "6.8 L/100km",
                            Horsepower = 136,
                            IsDeleted = false,
                            LicensePlate = "TM06RRR",
                            Location = "Timișoara",
                            Model = "Sportage",
                            PricePerDay = 55.00m,
                            Seats = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 40,
                            Brand = "Kia",
                            Chassis = "Hatchback",
                            Description = "Practical hatchback designed in Europe with spirited T-GDI engine and intuitive tech.",
                            EngineType = "1.0L T-GDI Petrol",
                            FabricationYear = 2023,
                            FuelConsumption = "5.0 L/100km",
                            Horsepower = 120,
                            IsDeleted = false,
                            LicensePlate = "B15RRR",
                            Location = "București",
                            Model = "Ceed",
                            PricePerDay = 42.00m,
                            Seats = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 41,
                            Brand = "Skoda",
                            Chassis = "Sedan",
                            Description = "Spacious sedan with German platform engineering, TSI petrol power and clever details.",
                            EngineType = "1.5L TSI Petrol",
                            FabricationYear = 2024,
                            FuelConsumption = "4.8 L/100km",
                            Horsepower = 150,
                            IsDeleted = false,
                            LicensePlate = "B16RRR",
                            Location = "București",
                            Model = "Octavia",
                            PricePerDay = 50.00m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 42,
                            Brand = "Skoda",
                            Chassis = "Sedan",
                            Description = "Efficient diesel sedan with class-leading boot space and comfortable long-distance ride.",
                            EngineType = "2.0L TDI Diesel",
                            FabricationYear = 2022,
                            FuelConsumption = "5.2 L/100km",
                            Horsepower = 150,
                            IsDeleted = false,
                            LicensePlate = "CJ09RRR",
                            Location = "Cluj-Napoca",
                            Model = "Octavia",
                            PricePerDay = 50.00m,
                            Seats = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 43,
                            Brand = "Skoda",
                            Chassis = "Sedan",
                            Description = "Executive-class space and comfort at a competitive price, powered by a refined TSI engine.",
                            EngineType = "2.0L TSI Petrol",
                            FabricationYear = 2024,
                            FuelConsumption = "5.5 L/100km",
                            Horsepower = 190,
                            IsDeleted = false,
                            LicensePlate = "BV07RRR",
                            Location = "Brașov",
                            Model = "Superb",
                            PricePerDay = 65.00m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 44,
                            Brand = "Skoda",
                            Chassis = "SUV",
                            Description = "Large 7-seat family SUV with clever storage solutions and capable TDI diesel.",
                            EngineType = "2.0L TDI Diesel",
                            FabricationYear = 2023,
                            FuelConsumption = "7.5 L/100km",
                            Horsepower = 200,
                            IsDeleted = false,
                            LicensePlate = "TM07RRR",
                            Location = "Timișoara",
                            Model = "Kodiaq",
                            PricePerDay = 75.00m,
                            Seats = 7,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 45,
                            Brand = "Renault",
                            Chassis = "Hatchback",
                            Description = "Stylish supermini with excellent fuel economy, nimble city handling and modern tech.",
                            EngineType = "1.0L SCe Petrol",
                            FabricationYear = 2024,
                            FuelConsumption = "4.2 L/100km",
                            Horsepower = 75,
                            IsDeleted = false,
                            LicensePlate = "B17RRR",
                            Location = "București",
                            Model = "Clio",
                            PricePerDay = 30.00m,
                            Seats = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 46,
                            Brand = "Renault",
                            Chassis = "Hatchback",
                            Description = "French flair meets practicality with a punchy TCe turbo and smooth automatic gearbox.",
                            EngineType = "1.3L TCe Petrol",
                            FabricationYear = 2023,
                            FuelConsumption = "4.8 L/100km",
                            Horsepower = 140,
                            IsDeleted = false,
                            LicensePlate = "IS06RRR",
                            Location = "Iași",
                            Model = "Megane",
                            PricePerDay = 45.00m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 47,
                            Brand = "Porsche",
                            Chassis = "SUV",
                            Description = "High-performance luxury SUV with twin-turbo V8, unmistakable Porsche DNA and sports car agility.",
                            EngineType = "4.0L V8 Twin-Turbo",
                            FabricationYear = 2024,
                            FuelConsumption = "11.5 L/100km",
                            Horsepower = 541,
                            IsDeleted = false,
                            LicensePlate = "B18RRR",
                            Location = "București",
                            Model = "Cayenne",
                            PricePerDay = 180.00m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 48,
                            Brand = "Porsche",
                            Chassis = "Coupe",
                            Description = "Iconic sports car delivering pure driving exhilaration with a legendary flat-six engine.",
                            EngineType = "3.0L Flat-6 Twin-Turbo",
                            FabricationYear = 2024,
                            FuelConsumption = "10.0 L/100km",
                            Horsepower = 450,
                            IsDeleted = false,
                            LicensePlate = "B19RRR",
                            Location = "București",
                            Model = "911",
                            PricePerDay = 250.00m,
                            Seats = 2,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 49,
                            Brand = "Volvo",
                            Chassis = "SUV",
                            Description = "Scandinavian luxury SUV focused on safety, mild hybrid efficiency and understated elegance.",
                            EngineType = "2.0L B5 Mild Hybrid Diesel",
                            FabricationYear = 2024,
                            FuelConsumption = "7.0 L/100km",
                            Horsepower = 235,
                            IsDeleted = false,
                            LicensePlate = "CJ10RRR",
                            Location = "Cluj-Napoca",
                            Model = "XC60",
                            PricePerDay = 95.00m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 50,
                            Brand = "Volvo",
                            Chassis = "SUV",
                            Description = "Flagship 7-seat SUV with world-leading safety technology and refined mild hybrid petrol power.",
                            EngineType = "2.0L B5 Mild Hybrid Petrol",
                            FabricationYear = 2023,
                            FuelConsumption = "8.5 L/100km",
                            Horsepower = 250,
                            IsDeleted = false,
                            LicensePlate = "BV08RRR",
                            Location = "Brașov",
                            Model = "XC90",
                            PricePerDay = 130.00m,
                            Seats = 7,
                            Transmission = "Automatic"
                        });
                });

            modelBuilder.Entity("CarRental.Core.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("CarRental.Core.Entities.RentalBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("RentalBookings");
                });

            modelBuilder.Entity("CarRental.Core.Entities.UnavailabilityPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("UnavailabilityPeriods");
                });

            modelBuilder.Entity("CarRental.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AccountBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountBalance = 0m,
                            Email = "admin@roadrunners.ro",
                            PasswordHash = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccountBalance = 20.00m,
                            Email = "client@roadrunners.ro",
                            PasswordHash = "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3",
                            Role = "Client",
                            Username = "client"
                        });
                });

            modelBuilder.Entity("CarRental.Core.Entities.Notification", b =>
                {
                    b.HasOne("CarRental.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarRental.Core.Entities.RentalBooking", b =>
                {
                    b.HasOne("CarRental.Core.Entities.Car", "Car")
                        .WithMany("RentalBookings")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.Core.Entities.User", "User")
                        .WithMany("RentalBookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarRental.Core.Entities.UnavailabilityPeriod", b =>
                {
                    b.HasOne("CarRental.Core.Entities.Car", "Car")
                        .WithMany("UnavailabilityPeriods")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CarRental.Core.Entities.Car", b =>
                {
                    b.Navigation("RentalBookings");

                    b.Navigation("UnavailabilityPeriods");
                });

            modelBuilder.Entity("CarRental.Core.Entities.User", b =>
                {
                    b.Navigation("RentalBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
